[default.extend-words]
gam = "gam"
sur = "sur"
l’approximation = "l’approximation" 
des = "des" 
équations = "équations" 
différentielles = "différentielles" 
opérationnelles = "opérationnelles" 
linéaires = "linéaires" 
par = "par" 
méthodes = "méthodes" 
de = "de" 
thèse = "thèse" 
d'état = "d'état"
